name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@master
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@master
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install tarball+https://install.devenv.sh/latest
    - name: Build the devenv shell and run any pre-commit hooks
      run: devenv ci
